fix: update args for zellij scripts

diff --git a/zellij-session-nav b/zellij-session-nav
--- a/zellij-session-nav
+++ b/zellij-session-nav
@@ -1,11 +1,8 @@
 #!/usr/bin/env bash
 
-if [[ -z $ZELLIJ_SWITCH_PATH ]]; then
-  echo "ZELLIJ_SWITCH_PATH is not set"
-  exit 1
-fi
-
-plugin="file://$ZELLIJ_SWITCH_PATH"
+plugin=""
+mode=""
+session_number=0
 
 list_sessions() {
   if [ "$1" == "true" ]; then
@@ -16,37 +13,47 @@ list_sessions() {
 }
 
 HEADLESS_MODE=false
-SESSION_NUMBER=0
 
 while [[ "$#" -gt 0 ]]; do
   case $1 in
+    --plugin) plugin="file://$2"; shift ;;
+    --mode) mode="$2"; shift ;;
+    --nr) session_number=$2; shift ;;
     --headless) HEADLESS_MODE=true ;;
-    *) SESSION_NUMBER=$1 ;;
+    *) session_number=$1 ;;
   esac
   shift
 done
+
+if [[ -z $plugin ]]; then
+  if [[ -z $ZELLIJ_SWITCH_PATH ]]; then
+    echo "ZELLIJ_SWITCH_PATH is not set"
+    exit 1
+  fi
+  plugin="file://$ZELLIJ_SWITCH_PATH"
+fi
 
 sessions=$(list_sessions "$HEADLESS_MODE")
 
 if $HEADLESS_MODE; then
   session_array=($sessions)
-  if [ "$SESSION_NUMBER" -ge 0 ] && [ "$SESSION_NUMBER" -lt "${#session_array[@]}" ]; then
-    session_name=${session_array[$SESSION_NUMBER]}
+  if [ "$session_number" -ge 0 ] && [ "$session_number" -lt "${#session_array[@]}" ]; then
+    session_name=${session_array[$session_number]}
     current_session=$(zellij ls | sed 's/\x1b\[[0-9;]*m//g' | grep '(current)' | awk '{print $1}')
     if [ "$session_name" == "$current_session" ]; then
-      echo "Already in session $SESSION_NUMBER ($session_name)"
+      echo "Already in session $session_number ($session_name)"
       exit 0
     else
-      zellij pipe --plugin $plugin -- "$session_name"
+      zellij pipe --plugin $plugin -- "--session $session_name"
     fi
   else
-    echo "Invalid session number: $SESSION_NUMBER"
+    echo "Invalid session number: $session_number"
     exit 1
   fi
 else
   session_name=$(echo "$sessions" | fzf)
   if [ -n "$session_name" ]; then
-    zellij pipe --plugin $plugin -- "$session_name"
+    zellij pipe --plugin $plugin -- "--session $session_name"
   else
     exit 0
   fi
